<a href="https://colab.research.google.com/github/crossorbit/hgmldl/blob/main/Ch_02_%EB%94%A5%EB%9F%AC%EB%8B%9D_%EA%B0%9C%EB%B0%9C_%EC%A4%80%EB%B9%84_Numpy_Tutorial_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

Numpy는 Numerical Python의 줄임말로, 파이썬에서 산술 계산을 위한 가장 중요한 패키지 중 하나입니다. 과학 계산을 위한 대부분의 패키지는 Numpy의 배열 객체를 데이터 교환을 위한 공통 언어처럼 사용합니다.

### Numpy 라이브러리 import

In [1]:
import numpy as np

### Numpy ndarray
Numpy의 핵심 기능 중 하나는 ndarray라고 하는 N차원의 배열 객체인데 파이썬에서 할 수 있는 대규모 데이터 집합을 담을 수 있는 빠르고 유연한 자료구조입니다.

In [2]:
a = np.array([1, 2, 3])
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


### List와 비교
List는 하나의 배열 안에 숫자,문자 섞어서 생성가능하나 Numpy는 동일한 타입만 가능함


In [3]:
L = [1, 2, 3]
A = np.array([1, 2, 3])
print(L)
print(A)

[1, 2, 3]
[1 2 3]


In [4]:
A

array([1, 2, 3])

In [5]:
for item in L:
  print(item)

1
2
3


In [6]:
for item in A:
  print(item)

1
2
3


In [7]:
L.append(4)
print(L)

[1, 2, 3, 4]


In [8]:
A = A.append(4)
print(A)

AttributeError: ignored

In [9]:
A = np.append(A, 4)
print(A)

[1 2 3 4]


In [10]:
L = L + [5]
print(L)

[1, 2, 3, 4, 5]


In [11]:
A = A + np.array([5])
print(A)

[6 7 8 9]


In [12]:
# list의 모든 원소를 2배로 만들기
L = [1, 2, 3]
L2 = []
for item in L:
  L2.append(item*2)
print(L2)

[2, 4, 6]


In [13]:
# ndarray의 모든 원소 2배로 만들기
A = np.array(L)
A2 = A*2
print(A2)

[2 4 6]


In [18]:
L * 2

[1, 2, 3, 1, 2, 3]

### 배열
numpy 배열은 모두 같은 유형의 값이며 음수가 아닌 정수의 튜플로 인덱싱됩니다. 차원의 수는 배열의 랭크입니다. 배열의 shape은 각 차원별 배열 크기의 튜플입니다.
중첩 된 파이썬 리스트로부터 numpy 배열을 초기화 할 수 있고 대괄호를 사용하여 요소에 접근 할 수 있습니다. 

#### 배열 생성하기

In [16]:
a = np.array([1, 2, 3])
print(a)
print(type(a), a.ndim, a.shape, a.dtype)

b = np.array([4, 5, 6])
print(b)
print(type(b), b.ndim, b.shape, b.dtype)

[1 2 3]
<class 'numpy.ndarray'> 1 (3,) int64
[4 5 6]
<class 'numpy.ndarray'> 1 (3,) int64


In [17]:
b = np.asarray(a) #asarray 로 바꾸면 a 를 같은 곳을 바라보고 있어서.  b[0] 적용 시 같이 바뀜. 
print(b)

[1 2 3]


In [19]:
b[0] = 9
print(a)
print(b)

[9 2 3]
[9 2 3]


In [20]:
c = np.array(a) # 새로운 카피본을 만들어냄
print(c)

[9 2 3]


In [21]:
c[0] = 1
print(a)
print(b)
print(c)

[9 2 3]
[9 2 3]
[1 2 3]


In [23]:
a = np.zeros((3,4))
print(a)
print(a.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64


In [ ]:
b = np.ones((5,2))
print(b)

In [24]:
c = np.full((2,3), 4)
print(c)

[[4 4 4]
 [4 4 4]]


In [25]:
d = np.empty((3,3))
print(d)

[[4.65632270e-310 2.42092166e-322 2.12199579e-314]
 [3.44620186e-085 4.34900767e+199 1.87422380e+261]
 [4.56782417e-085 9.30537465e+199 7.68290848e+170]]


In [26]:
e = np.zeros_like(a)
f = np.ones_like(a)
g = np.full_like(a, 2)
h = np.empty_like(a)
print(e)
print(f)
print(g)
print(h)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[4.65632273e-310 0.00000000e+000 7.92975362e-321 4.65632216e-310]
 [6.90075545e-310 4.65632216e-310 6.90075545e-310 6.90075545e-310]
 [0.00000000e+000 2.96439388e-323 2.12199579e-314 5.43472210e-323]]


In [28]:
i = np.eye(3) # 3x3 행렬 만드는데 대각선 방향 1로 채우기. np.eye(3, k=1) 변수 추가 시 k=1 두번째 열부터 1 채우기
k = np.eye(3, k=1) # 3x3 행렬 만드는데 대각선 방향 1로 채우기. np.eye(3, k=1) 변수 추가 시 k=1 두번째 열부터 1 채우기
j = np.identity(3) # 3x3 행렬 만드는데 대각선 방향 1로 채우기. 항등행렬
print(i)
print(k)
print(j)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
k = np.arange(10) # 0~9 까지 10개 숫자
k2 = np.arange(1,10) # 1~10까지
k3 = np.arange(10, 0, -1) # 10~1 까지 10개 숫자(역순)
print(k)
print(k2)
print(k3)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[10  9  8  7  6  5  4  3  2  1]


In [32]:
# uniform distribution
l = np.random.rand(2,2) # rand : 0~1 사이를 똑같은 확률로 뽑아줌
print(l)

[[0.34654064 0.83816349]
 [0.89977063 0.23749956]]


In [33]:
# normal distribution
m = np.random.randn(2,2) # randn : 표준 정규 분포에 따라 뽑아줌
print(m)

[[-1.11679561  0.7660336 ]
 [ 1.57583395 -0.12754094]]


#### 배열의 dtype

In [34]:
 a = np.array([1, 2, 3])
 b = np.array([1, 2, 3], dtype=np.float64)
 c = np.array([1, 2, 3], dtype=np.int32)

 print(a.dtype, b.dtype, c.dtype)

int64 float64 int32


In [35]:
d = np.array([1, 2, 3], dtype='i1')
e = np.array([1, 2, 3], dtype='i2')
f = np.array([1, 2, 3], dtype='i4')
g = np.array([1, 2, 3], dtype='i8')

print(d.dtype, e.dtype, f.dtype, g.dtype)

int8 int16 int32 int64


In [36]:
d = np.array([1, 2, 3], dtype='u1')
e = np.array([1, 2, 3], dtype='u2')
f = np.array([1, 2, 3], dtype='u4')
g = np.array([1, 2, 3], dtype='u8')

print(d.dtype, e.dtype, f.dtype, g.dtype)

uint8 uint16 uint32 uint64


In [37]:
h = np.array([1, 2, 3], dtype='f2')
i = np.array([1, 2, 3], dtype='f4')
j = np.array([1, 2, 3], dtype='f8')
k = np.array([1, 2, 3], dtype='f16')

print(h.dtype, i.dtype, j.dtype, k.dtype)

float16 float32 float64 float128


In [ ]:
# h = np.array([1, 2, 3], dtype='f2')
i = np.array([1, 2, 3], dtype='f')
j = np.array([1, 2, 3], dtype='d')
k = np.array([1, 2, 3], dtype='g')

print(h.dtype, i.dtype, j.dtype, k.dtype)

In [39]:
i = i.astype(np.int32) # astype : 타입 변경
print(i.dtype)

int32


In [40]:
j = j.astype(i.dtype) # i 의 dtype 으로 바꾸기
print(j.dtype)

int32


### 배열 indexing(색인)과 slicing(슬라이싱)



#### indexing, slicing 기본

In [41]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [42]:
# indexing
print(a[5])

5


In [43]:
# slicing
print(a[5:8]) # 5,6,7번째

[5 6 7]


In [44]:
print(a[-1]) # 맨 마지막

9


In [45]:
print(a[7:-1]) # 7에서 마지막 전까지.

[7 8]


In [46]:
a[5:8] = 10
print(a)

[ 0  1  2  3  4 10 10 10  8  9]


#### indexing과 slicing의 차이
indexing을 사용하면 항상 랭크(차원)가 감소합니다. 
 - 인덱싱 하기전에는 [ 5 ] 1차원 이였는데, 인덱싱 후 5 로 0차원으로 바뀜.
  
반면에 slicing을 사용하면 차원이 유지됩니다.

In [47]:
b = np.arange(1, 13)
# b = b.reshape(3, 4)
print(b)
print(b.shape) # 차원(랭크)
print(b.ndim) 

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
1


In [49]:
indexing = b[1]
slicing = b[1:2]
print(indexing, indexing.shape, indexing.ndim) # shape : 0차
print(slicing, slicing.shape, slicing.ndim) # shape : 1차

2 () 0
[2] (1,) 1


이것은 indexing과 slicing을 함께 사용할 때도 마찬가지입니다. indexing의 개수만큼 랭크는 감소합니다.

In [50]:
b = b.reshape(3, 4)
print(b)
print(b.shape)
print(b.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2


In [51]:
row_r1 = b[1, :]
row_r2 = b[1:2, :]
print(row_r1, row_r1.shape, row_r1.ndim)
print(row_r2, row_r2.shape, row_r2.ndim)

[5 6 7 8] (4,) 1
[[5 6 7 8]] (1, 4) 2


#### slicing examples

In [52]:
c = np.arange(24).reshape(2,3,4)
print(c)
print(c.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


In [53]:
print(c[:,:,:1])
print(c[...,:1])

[[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]
[[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]


In [54]:
print(c[0:1])
print(c[0::-1])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


#### boolean indexing

In [55]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [56]:
bool_idx = (c > 10)
print(bool_idx)

[[[False False False False]
  [False False False False]
  [False False False  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]


In [57]:
print(c[bool_idx])

[11 12 13 14 15 16 17 18 19 20 21 22 23]


In [60]:
c[c>10] = -1
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 -1]]

 [[-1 -1 -1 -1]
  [-1 -1 -1 -1]
  [-1 -1 -1 -1]]]


#### fancy indexing

In [61]:
d = np.arange(8).reshape(8,-1)
print(d, d.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] (8, 1)


In [62]:
d = np.hstack((d, d, d, d)) # 가로 방향으로 4개를 붙여라
print(d, d.shape)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]] (8, 4)


In [63]:
print(d[[3, 5, 1, 0]])

[[3 3 3 3]
 [5 5 5 5]
 [1 1 1 1]
 [0 0 0 0]]


In [64]:
print(d[[-3, -5, -7]])

[[5 5 5 5]
 [3 3 3 3]
 [1 1 1 1]]


In [65]:
e = np.arange(32).reshape(8,4)
print(e, e.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] (8, 4)


In [66]:
print(e[[1,5,7,2], [0,3,1,2]])

[ 4 23 29 10]


In [67]:
print(e[[1,5,7,2]][:, [0,3,1,2]])

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


### Transpose

In [82]:
f = np.arange(16).reshape(2,2,4)
print(f, f.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4)


In [85]:
print(f.transpose(1, 0, 2)) #순서 바꾸기. 텐서플로우와 파이토치가 이미지를 구분할 때 순서가 다름. height, width, channel. 그때 사용
#print(np.transpose(f))

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [70]:
print(f.swapaxes(0, 1))

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


### Numpy 연산

In [86]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [87]:
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [88]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [89]:
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [90]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [91]:
print(x @ y)
print(np.matmul(x, y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [92]:
z = np.arange(1, 11).reshape(2, 5)
print(z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [93]:
print(np.sum(z))

55


In [95]:
sum1 = np.sum(z, axis=0)
sum2 = np.sum(z, axis=1)
sum3 = np.sum(z, axis=-1)
print(sum1, sum1.shape)
print(sum2, sum2.shape)
print(sum3, sum3.shape)

[ 7  9 11 13 15] (5,)
[15 40] (2,)
[15 40] (2,)


여기서 축(axis)은 각 배열의 차원에 해당되는 index 입니다.

axis=0에 대하여 sum을 하라는 것은 0번 축 혹은 차원이 없어지는 방향으로 원소들을 모두 더하라는 얘기입니다.

즉, 위 예에서 sum1의 경우, z[0,:]+z[1,:]의 연산을 하라는 의미이고,

sum2의 경우에는 z[:,0]+z[:,1]+z[:,2]+z[:,3]+z[:,4]의 연산을 하라는 의미입니다.

In [96]:
print(z[0,:] + z[1,:])

[ 7  9 11 13 15]


In [97]:
print(z[:,0] + z[:,1] + z[:,2] + z[:,3] + z[:,4])

[15 40]


### Broadcasting

Broadcasting은 numpy가 산술 연산을 수행 할 때 다른 모양의 배열로 작업 할 수있게 해주는 강력한 메커니즘입니다. 종종 더 작은 배열과 더 큰 배열이 있을 때 더 작은 배열을 여러 번 사용하여 더 큰 배열에서 어떤 연산을 수행하기를 원할 때가 있습니다.

예를 들어, 행렬의 각 행에 상수 벡터를 추가하려 한다고 가정합시다. numpy에서는 다음과 같이 할 수 있습니다.

In [100]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
y = np.array([1,0,2])

In [101]:
print(x, x.shape)
print(y, y.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)
[1 0 2] (3,)


In [102]:
z = x + y
print(z, z.shape)

[[ 2  2  5]
 [ 5  5  8]
 [ 8  8 11]
 [11 11 14]] (4, 3)


z = x + y 는 broadcasting으로 인해 x가 shape (4, 3)이고 y가 shape (3)인데도 작동합니다. 이 행은 y가 실제로 shape (4, 3)인 것처럼 작동합니다. 각 행은 y의 사본이었고, 합계는 요소별로 수행되었습니다.

두 개의 배열을 브로드캐스팅하는 것은 다음 규칙을 따릅니다.

1. 배열의 랭크가 같지 않으면 두 모양이 같은 길이가 될 때까지 배열의 낮은 랭크쪽에 1을 붙입니다.
2. 두 배열은 차원에서 크기가 같거나 배열 중 하나의 차원에 크기가 1 인 경우 차원에서 호환 가능하다고 합니다.
3. 배열은 모든 차원에서 호환되면 함께 broadcast 될 수 있습니다.
4. Broadcast 후 각 배열은 두 개의 입력 배열의 요소 모양 최대 개수와 동일한 모양을 가진 것처럼 동작합니다.
5. 한 배열의 크기가 1이고 다른 배열의 크기가 1보다 큰 차원에서 첫 번째 배열은 마치 해당 차원을 따라 복사 된 것처럼 작동합니다

실제로 동작하는 방식을 생각해 봅시다.

1. A와 B의 모양을 생각합니다.
2. 두 배열이 len(A.shape) == len(B.shape)인지 확인을 합니다.
3. 같지 않은 경우에는 두 배열의 모양 길이가 같아질때까지 적은 쪽의 shape 앞에 1 을 추가해 줍니다.
- 예: (5,3)–>(1,5,3)
4. shape이 1인 곳은 복사가 됩니다.
- 예: shape의 변화는 아래와 같게 될겁니다.
- (5, 3)+(3,)
- (5, 3)+(1, 3)
- (5, 3) + (5, 3)
- (5, 3)

이 설명이 이해가되지 않으면 문서 또는 이 설명을 읽으십시오.

https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html

http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc

Broadcasting을 지원하는 함수들을 보편 함수라고합니다. 이 문서에서 모든 보편 함수 목록을 찾을 수 있습니다.
https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs


In [103]:
x = np.array([1,2,3]).reshape(1,3)
y = np.array([4,5]).reshape(1,2)
print(x, x.shape)
print(y, y.shape)

[[1 2 3]] (1, 3)
[[4 5]] (1, 2)


In [104]:
# broadcasting 조건에 맞지 않음
print(x + y)

ValueError: ignored

In [105]:
y = y.swapaxes(0, 1)
print(y, y.shape)

[[4]
 [5]] (2, 1)


In [106]:
# broadcasting 발생
print(x + y)

[[5 6 7]
 [6 7 8]]


### Shape 변경

In [107]:
a = np.arange(24).reshape(2,3,4)
print(a, a.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] (2, 3, 4)


In [108]:
a = a.reshape(4, -1)
print(a, a.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] (4, 6)


In [109]:
a = a[..., np.newaxis]
print(a, a.shape)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]
  [16]
  [17]]

 [[18]
  [19]
  [20]
  [21]
  [22]
  [23]]] (4, 6, 1)


In [110]:
a = a.reshape(4, 6)
a = np.expand_dims(a, axis=0)
print(a, a.shape)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]] (1, 4, 6)


In [111]:
b = a.copy()
print(b, b.shape)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]] (1, 4, 6)


In [112]:
c = np.concatenate((a, b), axis=-1)
print(c, c.shape)

[[[ 0  1  2  3  4  5  0  1  2  3  4  5]
  [ 6  7  8  9 10 11  6  7  8  9 10 11]
  [12 13 14 15 16 17 12 13 14 15 16 17]
  [18 19 20 21 22 23 18 19 20 21 22 23]]] (1, 4, 12)


In [113]:
c = np.concatenate((a, b), axis=0)
print(c, c.shape)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]] (2, 4, 6)


In [114]:
d = np.stack((a, b), axis=-1) # 스택을 쓰면 새로운 차원을 하나 더 만들어 추가함
print(d, d.shape)

[[[[ 0  0]
   [ 1  1]
   [ 2  2]
   [ 3  3]
   [ 4  4]
   [ 5  5]]

  [[ 6  6]
   [ 7  7]
   [ 8  8]
   [ 9  9]
   [10 10]
   [11 11]]

  [[12 12]
   [13 13]
   [14 14]
   [15 15]
   [16 16]
   [17 17]]

  [[18 18]
   [19 19]
   [20 20]
   [21 21]
   [22 22]
   [23 23]]]] (1, 4, 6, 2)


In [115]:
d = np.stack((a, b), axis=0)
print(d, d.shape)

[[[[ 0  1  2  3  4  5]
   [ 6  7  8  9 10 11]
   [12 13 14 15 16 17]
   [18 19 20 21 22 23]]]


 [[[ 0  1  2  3  4  5]
   [ 6  7  8  9 10 11]
   [12 13 14 15 16 17]
   [18 19 20 21 22 23]]]] (2, 1, 4, 6)
